### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by ericras** [unlcms/UNL-CMS#439]
Command line to run all tests:

```
sudo -u _www php ./scripts/run-tests.sh --url http://ucommrasmussen.unl.edu/workspace/drupal --all
```

Here's someone's stab at a Travis-ci script: https://github.com/unn/drupal-travis-ci/blob/master/.travis.yml

```
language: php

php:
  - 5.4

mysql:
  database: drupal
  username: root
  encoding: utf8

before_script:
 - mysql -e 'create database drupal;'
 - pyrus channel-discover pear.drush.org
 - pyrus install drush/drush
 - phpenv rehash
 - drush dl --yes drupal
 - cd drupal-*
 - drush si standard --db-url=mysql://root:@localhost/drupal --yes
 - drush en --yes simpletest
 - drush cc all
 - drush runserver --server=builtin 8080 &
 - sleep 4
 - drush vset --yes simpletest_verbose FALSE

script: php ./scripts/run-tests.sh --php /home/vagrant/.phpenv/shims/php --url http://127.0.0.1:8080 Tracker
```
