### ISSUE TITLE
Rework Menu Block css in unl_wdn theme

### ISSUE THREAD

**Issue by ericras** [unlcms/UNL-CMS#552]
Need to get rid of this:

``` css
.block-menu-block .content > ul > li > a {display: none;}
```

When I was first creating Menu Blocks I started them at the wrong level and wanted to hide the root:
(Inspect element:) http://payroll.unl.edu/policies/list

The real solution is to start the Menu Block one more level down.
